language: node_js
node_js:
- '10'
dist: trusty
sudo: required
services: postgresql
addons:
  ssh_known_hosts:
  - git.example.com
  - 51.38.49.215
before_script:
- psql -c 'create database test;' -U postgres
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_7382dfd1c392_key -iv $encrypted_7382dfd1c392_iv
  -in encryptFiles.tar.enc -out encryptFiles.tar -d
- tar xvf encryptFiles.tar
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@51.38.49.215 pwd

after_success:
- ls -al /bin/sh && sudo rm /bin/sh && sudo ln -s /bin/bash /bin/sh && ls -al /bin/sh
- sudo apt-get install git
- git config --global user.email "simon.lelut@gmail.com"
- git config --global user.name "simonlelut"
- npm i pm2 -g
- pm2 deploy ecosystem.json production setup
- pm2 deploy ecosystem.json production
