language: node_js

services:
  - docker

before_install:
  - docker build -t simonlelut/nodeapi .
  - docker run -d -p 3000:3000 simonlelut/nodeapi

script:
  - docker run --rm simonlelut/nodeapi /bin/sh -c "npm run test"