version: '2.1'
services:
  node-api-rest:
    image: node-api-rest
    build: .
    environment:
      NODE_ENV: docker
    ports:
      - 80:3000
    volumes:
      - .:/node-api-rest
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql