apiVersion: v1
kind: Service
metadata:
  name: node-api-rest
  labels:
    app: node-api-rest
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: node-api-rest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-rest-deployment
  labels:
    app: node-api-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-api-rest
  template:
    metadata:
      labels:
        app: node-api-rest
    spec:
      containers:
      - name: node-api-rest
        image: simonlelut/nodeapi
        ports:
        - containerPort: 80