swagger: "2.0"
info:
  version: "1.0.0"
  title: API
  description: "Documentation de l'API"

schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      description: Returns all users
      produces:
      - application/json
      responses:
        '200':
          description: A list of users.
          schema:
            type: array
            items:
              
            
type: object
required:
- name
- id
properties:
  id:
    type: integer
  name:
    type: string
  
  
