swagger: "2.0"
info:
  version: 1.0.0
  title: User api
  description: Nice API / test deploy 4
basePath: /users
tags:
  - name: Users
    description: CRUD Users

consumes:
  - application/json
produces:
  - application/json

definitions:
  User:
    type: object
    title: Users
    required:
      - name
    properties:
      id: 
        type: number
        description: Id of user
      name:
        type: string
        description: Name of user
paths:
  /:
    get:
      tags:
        - Users
      description: Fetch all Users
      responses:
        200:
          description: Returns all users
    post:
      tags:
        - Users
      description: Create a new user
      parameters:
        - name: body
          in: body
          description: name
          required: true
          schema: 
            $ref: "#/definitions/User"
      responses:
        201:
          description: Returns User

  /{id}:
    get:
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: string
      responses:
        200:
          description: Return the user with the specified id
        404:
          description: Don't know any user with this id
    put:
      tags:
        - Users
      description: Update user
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: string
        - name: body
          in: body
          description: name
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: Returns String
        404:
          description: Don't know any user with this id
    delete:
      tags:
        - Users
      description: Delete user
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to delete
          type: string
      responses:
        200:
          description: Returns String
        404:
          description: Don't know any user with this id